name: ShatteredCore
description: A library of libraries, for the ShatteredSuite.
main: com.github.shatteredsuite.core.plugin.ShatteredCore
version: @version@
api-version: "1.17"
website: @website@
libraries:
  - "org.jetbrains.kotlin:kotlin-reflect:@kotlinVersion@"
  - "org.jetbrains.kotlin:kotlin-stdlib:@kotlinVersion@"
  - "com.google.code.gson:gson:@gsonVersion@"
  - "com.fasterxml.jackson.core:jackson-core:@jacksonVersion@"
  - "com.fasterxml.jackson.core:jackson-databind:@jacksonVersion@"
  - "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:@jacksonVersion@"
  - "com.h2database:h2:@h2Version@"
  - "com.zaxxer:HikariCP:@hikariVersion@"
authors:
  - UberPilot

permissions:
  shatteredcore.command.about:
    default: op
    description: "Displays information about this library."

commands:
  shatteredcore:
    usage: /shatteredcore
    description: "Shows information about this plugin."