name: ShatteredCore
description: A library of libraries, for the ShatteredSuite.
main: com.github.shatteredsuite.core.plugin.ShatteredCore
version: @version@
api-version: "1.17"
website: @website@
libraries:
  - "org.jetbrains.kotlin:kotlin-reflect:1.5.30"
  - "org.jetbrains.kotlin:kotlin-stdlib:1.5.30"
  - "com.google.code.gson:gson:2.8.7"
authors:
  - UberPilot

permissions:
  shatteredcore.command.about:
    default: op
    description: "Displays information about this library."

commands:
  shatteredcore:
    usage: /shatteredcore
    description: "Shows information about this plugin."